services:
  - type: web
    name: rmc-delivery-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PORT
        value: 8000
