"""
Domain events — notifications of important state changes.

Events are:
  - Immutable (frozen dataclasses)
  - Timestamped with a unique event_id
  - Self-describing via event_type property (CamelCase → snake_case)
  - Carry all context needed by handlers
  - Never perform I/O themselves

They flow through the AlertService (Observer pattern) to reach
SSE clients, structured logging, SMS/email handlers, or dashboards.

Event hierarchy:
  DomainEvent (base)
  ├── LoadBatched            — concrete loaded onto truck
  ├── LoadStatusChanged      — FRESH → WARNING → CRITICAL
  ├── LoadExpired            — load exceeded usable life
  ├── RetarderRecommended    — system recommends retarder
  ├── FeasibilityChecked     — pre-dispatch assessment result
  ├── RerouteCritical        — reroute while load is at risk
  └── DeliveryInfeasible     — can't deliver before load expires
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional
from uuid import uuid4

from app.domain.enums import AlertSeverity, FeasibilityResult, LoadStatus


# ─────────────────────────────────────────────────────────────────────────────
# Base Event
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class DomainEvent:
    """
    Base class for all domain events.

    Every event gets a unique event_id and a UTC timestamp automatically.
    Subclasses add domain-specific fields.
    """

    event_id: str = field(default_factory=lambda: uuid4().hex[:12])
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def event_type(self) -> str:
        """Snake-case event name derived from the class name."""
        name = type(self).__name__
        return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()

    def to_dict(self) -> dict:
        """Serialize for JSON logging / SSE payloads."""
        result: dict = {}
        for key, value in self.__dict__.items():
            if isinstance(value, datetime):
                result[key] = value.isoformat()
            elif hasattr(value, "value"):  # Enum
                result[key] = value.value
            else:
                result[key] = value
        result["event_type"] = self.event_type
        return result


# ─────────────────────────────────────────────────────────────────────────────
# Load Lifecycle Events
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class LoadBatched(DomainEvent):
    """Concrete has been batched and loaded onto the truck."""

    trip_id: int = 0
    mix_code: str = ""
    volume_m3: float = 0.0
    max_life_minutes: int = 90
    expiry_time: str = ""  # ISO format


@dataclass(frozen=True)
class LoadStatusChanged(DomainEvent):
    """
    Load status transitioned (e.g., FRESH → WARNING).

    Generated by LoadManager.evaluate() on each traffic check cycle
    when the status differs from the previous check.
    """

    trip_id: int = 0
    previous_status: LoadStatus = LoadStatus.FRESH
    new_status: LoadStatus = LoadStatus.WARNING
    minutes_remaining: float = 0.0
    eta_minutes: Optional[float] = None
    action_required: str = ""
    severity: AlertSeverity = AlertSeverity.WARNING


@dataclass(frozen=True)
class LoadExpired(DomainEvent):
    """
    Load has exceeded its usable life — concrete cannot be poured.

    This is an EMERGENCY severity event. Dispatcher and site foreman
    must be notified immediately.
    """

    trip_id: int = 0
    minutes_over: float = 0.0
    was_retarded: bool = False
    severity: AlertSeverity = AlertSeverity.EMERGENCY


@dataclass(frozen=True)
class RetarderRecommended(DomainEvent):
    """
    System recommends adding chemical retarder to extend load life.

    This event fires when the load's remaining life is projected to be
    insufficient for the current ETA, but retarder would fix it.
    """

    trip_id: int = 0
    current_minutes_remaining: float = 0.0
    eta_minutes: float = 0.0
    recommended_extension_minutes: int = 45
    severity: AlertSeverity = AlertSeverity.WARNING


# ─────────────────────────────────────────────────────────────────────────────
# Feasibility Events
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class FeasibilityChecked(DomainEvent):
    """
    Result of a pre-dispatch feasibility assessment.

    Published by the DispatchEngine for each candidate plant.
    """

    trip_id: int = 0
    result: FeasibilityResult = FeasibilityResult.FEASIBLE
    travel_minutes: float = 0.0
    max_allowed_minutes: float = 90.0
    plant_id: Optional[str] = None
    reason: str = ""
    severity: AlertSeverity = AlertSeverity.INFO


# ─────────────────────────────────────────────────────────────────────────────
# Reroute + Traffic Events
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class RerouteCritical(DomainEvent):
    """
    Reroute triggered while the load is in WARNING or CRITICAL status.

    Higher urgency than a normal reroute — dispatcher needs to decide
    whether to continue delivery or abort.
    """

    trip_id: int = 0
    load_status: LoadStatus = LoadStatus.WARNING
    minutes_remaining: float = 0.0
    new_eta_minutes: float = 0.0
    will_expire_en_route: bool = False
    severity: AlertSeverity = AlertSeverity.CRITICAL


@dataclass(frozen=True)
class DeliveryInfeasible(DomainEvent):
    """
    Current route cannot deliver before the load expires.

    This is the "point of no return" — the system has determined that
    even with the best-case route, concrete will expire before arrival.
    Dispatcher must act: cancel trip, divert to closer site, or accept waste.
    """

    trip_id: int = 0
    minutes_remaining: float = 0.0
    eta_minutes: float = 0.0
    shortfall_minutes: float = 0.0
    severity: AlertSeverity = AlertSeverity.EMERGENCY
    recommended_action: str = ""
